### ISSUE TITLE
Poor recognition of tests

### ISSUE THREAD

**Issue by stimm81** [etas/vs-boost-unit-test-adapter#200]
Hi,
we recently observed that on many developer machines the recognition of boost tests in the test explorer windows is not very stable. The developers report that in such a case only a subset of tests or even no tests at all are recognized. Sometimes a rebuild helps, sometimes not even that helps.

Here are some log entries of the Output window of Visual Studio 2015:
```
2017-05-10 15:39:39,987 [20376] INFO  Logger initialized. Logging to C:\USERS\KBB9FE\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\HGD0X2DK.YL1\BoostTestAdapter.dll.log
2017-05-10 15:41:32,939 [12788] INFO  Logger initialized. Logging to C:\USERS\KBB9FE\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\HGD0X2DK.YL1\BoostTestAdapter.dll.log
2017-05-10 15:41:33,008 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\binTest\Etas.Client.Concurrency.TestClient.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:41:40,693 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\Etas.Infrastructure.AcceptanceTest.Boostd.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:41:44,834 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\Etas.Infrastructure.Utility.NlsSourceGeneratord.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:41:47,741 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreBase.Maind.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:42:53,710 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.CalcEngine.BcFileGend.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:43:04,766 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.MdfFileGend.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:43:16,116 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.Online.Xcp.MasterSlaveExecution.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:43:19,343 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\MdfConvertd.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:43:24,283 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\MdfExtractd.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:43:28,221 [12788] WARN  Could not locate debug symbols for 'C:\McdCore\Install\bin\x64\MdfRecoveryTool.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
2017-05-10 15:43:28,224 [12788] INFO  Discovering (ListContentDiscoverer):   -> [C:\McdCore\Install\bin\x64\Etas.Infrastructure.Base.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.Infrastructure.CommunicationFramework.IceLogging.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.Infrastructure.Coroutines.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.Infrastructure.Execution.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.Infrastructure.Utility.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreBase.CoreApi.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreBase.Eventing.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreBase.Main.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreBase.TargetDescriptionModel.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreBase.TestApiExtensionQuery.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.CalcEngine.BcFileGen.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.CalcEngine.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.ConnectionManager.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.DataAccess.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.ErrorDescription.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.SignalDescription.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.SignalProcessing.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.CoreServices.TimeShift.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.AsciiCommon.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Dummy.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Dxl.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Example.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.LabFile.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Mdf.BlockLayer.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Mdf.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Mdf3.BlockLayer.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Mdf3.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Mdf4.BlockLayer.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Mdf4.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.MdfFileGen.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Pems.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Formats.Tsv.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.MdfConvert.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.MdfExtract.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.MeasureFile.Setup.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.Online.Dummy.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.Online.VirtualEthernet.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.Online.Xcp.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.TargetAccess.Targets.VirtualTarget.Test.Boostd.exe, C:\McdCore\Install\bin\x64\Etas.UnitTestFramework.Test.Boostd.exe]
2017-05-10 15:43:28,997 [12788] ERROR Exception caught while discovering tests: IRunningObjectTable::GetObject returned with code:-2147023174 (-2146233088)
2017-05-10 15:43:29,025 [12788] DEBUG    at BoostTestAdapter.Utility.NativeMethods.<get_RunningObjectTable>d__4.MoveNext()
   at BoostTestAdapter.Utility.VisualStudio.DefaultVisualStudioInstanceProvider.GetSolutionObject(String processId)
   at BoostTestAdapter.Utility.VisualStudio.DefaultVisualStudioInstanceProvider.get_Instance()
   at BoostTestAdapter.Discoverers.ListContentDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, ITestCaseDiscoverySink discoverySink)
   at BoostTestAdapter.BoostTestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, ITestCaseDiscoverySink discoverySink)
```
This issue occurs with the latest version of Boost Unit test adapter (1.0.8.44).
In case you need more information, please reply to this comment.

**Comment by guwirth** [comment]
@stimm81 does this also occur if only Boost Unit test adapter is installed or only in combination with NUnit test adapter?
