### ISSUE TITLE
Unable to discover test

### ISSUE THREAD

**Issue by candychiu** [etas/vs-boost-unit-test-adapter#92]
Hi, I encountered an issue discovering tests in Visual Studio 2013 Update 5.  My teammate who also has the same set up as mine did not encounter this issue.  

------ Discover test started ------
Logger initialized. Logging to C:\USERS\SomeUser\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\CK5IRDWE.3CK\BoostTestAdapter.dll.log
Discovering (SourceCodeDiscoverer):   -> [C:\Users\SomeUser\MyProject\build\bin\Test-gd.exe]
Exception caught while discovering tests: IRunningObjectTable::GetObject returned with code:-2147220997 (-2146233088)
   at BoostTestAdapter.Utility.NativeMethods.get_RunningObjectTable()
   at BoostTestAdapter.Utility.VisualStudio.DefaultVisualStudioInstanceProvider.GetSolutionObject(String processId)
   at BoostTestAdapter.Utility.VisualStudio.DefaultVisualStudioInstanceProvider.get_Instance()
   at BoostTestAdapter.Discoverers.SourceCodeDiscoverer.PrepareTestCaseData(IEnumerable`1 sources)
   at BoostTestAdapter.Discoverers.SourceCodeDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
   at BoostTestAdapter.BoostTestDiscoverer.DiscoverTests(IEnumerable`1 sources, IDiscoveryContext discoveryContext, ITestCaseDiscoverySink discoverySink)
========== Discover test finished: 0 found (0:00:00.3090309) ==========

**Comment by netspiri** [comment]
Hi @candychiu,

This seems to be an [CO_E_OBJNOTREG](https://msdn.microsoft.com/en-us/library/windows/desktop/dd542643(v=vs.85).aspx) COM error code. This happens when trying to access the current Visual Studio running instance so that we can iterate over the project files. Will look further into this when we have the time.

**Comment by candychiu** [comment]
The problem went away on itself own.  Thanks.
